### ISSUE TITLE
Connect search to UCI, make bot runnable

### ISSUE THREAD

**Issue by morphe157** [marekpiotradamczyk/bestiazwroclawia#15]
We want to connect UCI `go`and `position` commands to search.
`go depth 5` should run search with given depth,
on finish it should output `bestmove <move>`
where move is in format [a-h][1-8][a-h][1-8]

`position` command should set root position for search.

Sample input
```
position startpos moves e2e4
go depth 3
``` 
Sample output
```
bestmove e7e5
```

Optional: check if we can find mate in 2 :-)
```
position fen r1bq2r1/b4pk1/p1pp1p2/1p2pP2/1P2P1PB/3P4/1PPQ2P1/R3K2R w
go depth 3
```

**Comment by mateusz2173** [comment]
should be done after #10 is done
