### ISSUE TITLE
Podstawka - bitboardy

### ISSUE THREAD

**Issue by mateusz2173** [marekpiotradamczyk/bestiazwroclawia#8]
DoD:
- [ ] Znaleźć jakąś libke/plik.cpp/hpp implementujący logikę generowania ruchów za pomocą bitboardów, nie musi być wybitnie szybka
- [ ] Dodać do repo wraz z Makefile (lub CMakeLists) który ją skompiluje i prostym przykładem użycia.

**Comment by Gustav2137** [comment]
https://github.com/nkarve/surge zdaje się w porządku, jak do końca tygodnia nie pojawi się nic lepszego to ja bym brał tą

**Comment by olekluka** [comment]
Taką bibliotekę znalazł niedawno mój brat: https://github.com/Disservin/chess-library.

Patrząc na benchmarki to jest wyraźnie szybsza niż Surge. Oprócz tego oferuje wiele dodatkowych funkcji i ma porządnie zrobioną dokumentację.

**Comment by mateusz2173** [comment]
Wygląda dobrze
